### ISSUE TITLE
linux make之后怎么跑通啊

### ISSUE THREAD

**Issue by konL** [WangZhengru/sql-parser#2]
make 之后生成了很多文件，想编译parser.tab.c运行来着，有错误没跑通....

parser.tab.c:(.text+0x4657): undefined reference to `ast_root'

在linux 输入了两行命令也报错啊
[hadoop@hadoop000 sql-parser-master]$ #include "ast.h"
[hadoop@hadoop000 sql-parser-master]$ link libparser.a 
link: missing operand after ‘libparser.a’
Try 'link --help' for more information.

请问一下make之后在linux怎么才能跑通.....

**Comment by wzru** [comment]
#include "ast.h" 应该放在你的C/C++代码里面，用来引入头文件
link libparser.a是指链接的时候要链接这个编译出来的静态库

**Comment by konL** [comment]
你好，谢谢你的回答。但我还没理解....
是这样的，我根据您的教程，make编译之后生成了几个文件，
1. 我想问的是下一步该运行哪个文件我才可以生成ast树呢？
2. 我看了其中的文件，看到parser.tab.c中就有parse_sql(char *sql)这个函数，从代码上看，应该是运行这个文件，成功之后会让我输入sql语句，然后就可以输出ast树了是吗？
感谢您的耐心解答！

**Comment by wzru** [comment]
接下来你应该写一个C/C++程序来调用这个函数，例如这里我在sql-parser目录下新建了一个main.c：
```c
#include "ast.h"

int main()
{
    char *sql = "SELECT * FROM TABLE;";
    SqlAst *ast = parse_sql(sql);
    print_ast(ast, 0);
    return 0;
}
```
然后在命令行中编译，注意要使用-L和-l参数来链接对应的libparser.a库：
```bash
gcc main.c -o main -L. -lparser
```
然后运行./main：
```bash
shaun@ShawnO:~/sql-parser$ ./main
{
        type: SELECT,
        columns: [
        {
                type: *
        }
        ],
}
```

**Comment by wzru** [comment]
对于打印AST的部分，建议还是自己定义函数来打印符合自己要求的格式，具体的AST结构体定义在ast.h中。

**Comment by konL** [comment]
理解了，谢谢回答！会的，我尝试自己根据课设要求修改一下，其他方面的修改我自己没有太大的问题。😀
